pipeline {
    agent { node { label 'worker1' } }
    
    tools {
        maven 'mvn3.9.13' 
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'checkout...'
                    git branch: 'main',
                    credentialsId: 'GitHub',
                    url: 'https://github.com/anamarina-95/Siem_InterviewProject.git'
		    }
        }
        
        stage('Compile') {
            steps {
                echo 'compile...'
                    sh 'mvn compile'
		    }
        }
        
        stage('Codereview-Pmd') {
            steps {
                echo 'codereview...'
                    sh 'mvn -P metrics pmd:pmd'
		    }
		    post {
		        success {
		            recordIssues enabledForFailure: true, tool: pmdParser(pattern: '**/target/pmd.xml')
		        }
		    }		
        }
        
        stage('Unit-Test') {
            steps {
                echo 'unittest...'
                    sh 'mvn test'
                
            }
            post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }			
        }
        
        stage('CodeCoverage') {
            steps {
                echo 'unittest..'
                    sh 'mvn verify'
            }
            post {
                success {
                    jacoco buildOverBuild: true, deltaBranchCoverage: '20', deltaClassCoverage: '20', deltaComplexityCoverage: '20', deltaInstructionCoverage: '20', deltaLineCoverage: '20', deltaMethodCoverage: '20'
                }
            }			
        }
        
        stage('Build') {
            steps {
                echo 'package....'
                    sh 'mvn package'	
            }		
        }
        
        stage('Build Docker Image') {
	    steps {
		sh 'cp /root/jenkins/workspace/$JOB_NAME/target/ABCtechnologies-1.0.war /root/jenkins/workspace/$JOB_NAME/'
		sh 'docker build --file Dockerfile --tag docker.io/anamarina95/abctechnologies:$BUILD_NUMBER .'
	    }
	}

	stage('Push Docker Image') { 
	    steps {   
		withDockerRegistry([ credentialsId: "DockerHub", url: "https://index.docker.io/v1/" ]) {
			sh 'docker push docker.io/anamarina95/abctechnologies:$BUILD_NUMBER'
		}
	    }
	}

	stage('deploy-Prod') {
            steps {
                sh script: 'ansible-playbook --inventory $WORKSPACE/deploy/inv $WORKSPACE/deploy/deploy-kube.yml --extra-vars "env=Prod build=$BUILD_NUMBER"'
	    }
	}   
    }
}
